#!/bin/bash
[ ! ${ENVDISCOVERY_G} ] && ENVDISCOVERY_G='ENVDISCOVERY' || return 0

#------------------------------------------------------------------------------------------
# Set to a valid directory to avoid and error.
[[ -e "/var/log/tomcat8/" ]] && TOMCAT_LOG_DIR="/var/log/tomcat8/" || TOMCAT_LOG_DIR=""


KOBOLD_DOMAIN=10.0.0.5
KNOCKER_DOMAIN=10.0.0.5
COBLYNAU_DOMAIN=10.0.0.5
PRIMROSE_DOMAIN=10.0.0.5
TURTLE_DOMAIN=10.0.0.3
#----------------------------------------------
# returns the current machines IP 
#----------------------------------------------
getIP () {
    ip address | grep 'inet 10' | cut -c 10-17
}

#----------------------------------------------
# returns the name of the OS
# usage: [ $(getOS) == "CentOS" ] && echo yes || echo no
#----------------------------------------------
getOS () {
  hostnamectl | grep Operating | cut -c 21-26
}

#----------------------------------------------
# returns true if this is the viewing computer
#----------------------------------------------
isViewingComputer () {
    [ ! isSSH ]
    return $?
}

isTurtleComputer () {
    [ getIP == "$TURTLE_DOMAIN" ] || isSimulated
    return $?
}

#----------------------------------------------
# returns true (0) if this is an ssh session
# example usage: isSSH && echo yes || echo no
#---------------------------------------------
isSSH () {
    SESSION_TYPE=console
    if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
    SESSION_TYPE=remote/ssh
    else
    case $(ps -o comm= -p $PPID) in
        sshd|*/sshd) SESSION_TYPE=remote/ssh;;
    esac
    fi

    [ $SESSION_TYPE == "remote/ssh" ]
    return $?
}

#----------------------------------------------
# Returns true if there are more than 4 log files
# in the tomcat log directory. 
#---------------------------------------------
isSimulated () {
    [ $(ls ${TOMCAT_LOG_DIR}*.log | grep -c '.log') -gt 4 ]
    return $?
}

#----------------------------------------------
#  Set the IP for each app.
#----------------------------------------------
setAppLocation () {
    if ! isSSH || isSimulated
    then 
        KOBOLD_DOMAIN=localhost
        KNOCKER_DOMAIN=localhost
        COBLYNAU_DOMAIN=localhost
        PRIMROSE_DOMAIN=localhost
        TURTLE_DOMAIN=localhost
    fi
}

setAppLocation
