#!/bin/bash
[ ! ${EDITFILES_G} ] && EDITFILES_G='EDITFILES' || return 0

. /home/powin/tools/snippets/color
. /home/powin/tools/snippets/cursor
. /home/powin/tools/shconfig/menucfg
. /home/powin/tools/snippets/generalFunctions


#-----------------------------------------------------------------------------------------------
#  Call the appropriate editor.
#-----------------------------------------------------------------------------------------------
editFile () {
  if isSSH
  then
    command="sudo nano $1"
  else
    command="sudo gedit $1"
  fi
  $command
}


#-----------------------------------------------------------------------------------------------
#
#-----------------------------------------------------------------------------------------------
function doEditFile {
  local TURTLEXML="$TURTLE_XML_PATH"
  local CONFIGJSON="$POWIN_PATH/configuration.json"
  local STACKSIM="$POWIN_PATH/stacksimulator.json"
  local PCSJSON="$POWIN_PATH/device/*20*.json"
  local menuItems=()
  local functions=()
  local filter=("$TURTLEXML" "$CONFIGJSON" "$STACKSIM" "$PCSJSON")

  for i in ${filter[@]}; do
    if [[ -e "$i" ]];
    then
      menuItems=("${menuItems[@]}" "$i")
      functions=("${functions[@]}" "(editFile $i)")
    fi
  done

  if [[ 0 -eq "${#menuItems[@]}" ]]; then  # TODO find the line #
     showInfoDialog "There are no configuration files on this system to edit." "No Files Found"
  else
     genMenu "Edit Files" "${menuItems[@]}" "${functions[@]}"
  fi

}
