#!/bin/bash
[ ! ${MANAGE_TOMCAT_G} ] && MANAGE_TOMCAT_G='MANAGETOMCAT' || return 0

. /home/powin/tools/snippets/color
. /home/powin/tools/snippets/cursor
. /home/powin/tools/shconfig/menucfg
. /home/powin/tools/snippets/generalFunctions

#-----------------------------------------------------------------------------------------------
# start tomcat
# -d flag will start tomcat up in debug mode
# verifies that tomcat is stopped
# removes files in the log folder older than 5 days
#-----------------------------------------------------------------------------------------------
function startTomcat() {
  local isTomcatRunning=$(/bin/systemctl status tomcat.service | grep running)
  [[ -e ${CATALINA_LOG_PATH}/catalina.out ]] && mv ${CATALINA_LOG_PATH}/catalina.out ${CATALINA_LOG_PATH}/${timestamp}_catalina.out.bk
  removeOldFiles ${CATALINA_LOG_PATH} 5
  if [[ ! $isTomcatRunning ]] ; then
    if [[ $# -ne 0 && $1 == *"-d"* ]] ;
    then
      tomcatDebug='true'
      sudo /opt/tomcat/bin/catalina.sh jpda start
    else
      sudo /bin/systemctl start tomcat.service ; waitTomcatStart
    fi
  else cntr ; echo -e "${LTGREEN}Tomcat is running.${RESET}"
  fi
}

#-----------------------------------------------------------------------------------------------
# stop tomcat
# verifies that tomcat is started
#
#-----------------------------------------------------------------------------------------------
function stopTomcat() {
   if [[ $( /bin/systemctl status tomcat.service | grep running) ]] ; then
    if [[ $tomcatDebug ]] ;
    then
      sudo /opt/tomcat/bin/catalina.sh stop
      unset tomcatDebug
    else
      cntr ; echo -ne "${YELLOW}Stopping Tomcat please wait"
      cntr ; sudo /bin/systemctl stop tomcat.service ; waitTomcatStop
    fi
  else
     cntr ; echo -e "${LTGREEN}Tomcat is stopped.${RESET}"
  fi
}

function restartTomcat() {
  cntr ; sudo service tomcat restart ; sudo less -n +F ${CATALINA_LOG_PATH}/catalina.out $1
}
#-----------------------------------------------------------------------------------------------
#
#-----------------------------------------------------------------------------------------------
function tailCatalina() {
  sudo less -n +F ${CATALINA_LOG_PATH}/catalina.out
}

#-----------------------------------------------------------------------------------------------
#
#-----------------------------------------------------------------------------------------------
function tailTurtle() {
 sudo less -n +F ${TOMCAT_LOG_DIR}/turtle.log
}

#-----------------------------------------------------------------------------------------------
#
#-----------------------------------------------------------------------------------------------
function doManageTomcat {
  local menuItems=('Stop Tomcat'  'Start Tomcat' 'Start Tomcat Debug'  'Restart Tomcat' ' Tail Catalina.out' 'Tail Turtle.log')
  local functions=('(stopTomcat);curDwn=1' '(startTomcat);curDwn=1' '(startTomcat -d);curDwn=1' '(restartTomcat);curDwn=1' '(tailCatalina);curDwn=1', '(tailTurtle);curDwn=1')
  genMenu "Tomcat Tasks" "${menuItems[@]}" "${functions[@]}"
}
