#!/bin/bash
. $HOME/tools/snippets/bootstrap
#-----------------------------------------------------------------------------------------------
#
#-----------------------------------------------------------------------------------------------
function do_backup {
    tar -czvf $HOME/backup.tgz ${HOME}/bin
}


#-----------------------------------------------------------------------------------------------
#
#-----------------------------------------------------------------------------------------------
setStackSimDisplay () {
  if isSimulated; then
    stackSimLine=$(getLineNum stack $TURTLE_XML_PATH)
    if [[ -z  stackSimLine ]] ;
    then
    sudo sed -i "9i<Parameter name=\"phoenix.stacksimulator.enabled\" value=\"true\" />" $TURTLE_XML_PATH
    fi
    local  value="$(sudo grep stacksimulator $TURTLE_XML_PATH | sed 's/.*value=//' | sed 's|/>||')"
    [[ "$value" =~ "true" ]] && stackSimON="$BOLD${LTGREEN}ON" || stackSimON="$BOLD${RED}OFF"
  fi
}
#-----------------------------------------------------------------------------------------------
#
#-----------------------------------------------------------------------------------------------
enableStackSim () {
  if isSimulated; then
    setStackSimDisplay
    local on=true
    local off=false
    if [[ $stackSimON =~ "OFF" ]] ; then
        on=false
        off=true
    fi
    sudo sed -i "${stackSimLine}s/${on}/${off}/" $TURTLE_XML_PATH
    setStackSimDisplay
    cntr ; echo -e "Setting stack simulator to $stackSimON${RESET}"
    cntr ; echo "Don't forget to restart Tomcat to pick up your changes!"
  fi
}



installApp () {
  local appMgr="$1"
  local app="$2"
  if ! command -v "$app" &> /dev/null
  then
    echo installing $app please wait.....
    sudo $appMgr install $app -y &> /dev/null
  fi
}

#-----------------------------------------------------------------------------------------------
# Initialize the app by loading all the supporting files.
# Install any missing packages
#   dialog for all machines and zenity for the viewing machine.
#-----------------------------------------------------------------------------------------------
function init () {
    clearLoadSemaphores
    loadSupportFiles
    local appMgr=yum                # assume centos
    if command -v apt               # check for ubuntu
    then
      appMgr=apt
    fi
    
    installApp $appMgr dialog       # use this when ssh
    installApp $appMgr mc           # just because its there
    if ! isSSH
    then 
       installApp $appMgr zenity    # graphic dialogs
    fi
}

#######
# Start of Script
main () {
setStackSimDisplay
isLiveStack=$(checkLiveStack)
local opt
menuItems=('Edit File' 'View Logs' 'Launch Midnight Commander' 'Manage Tomcat' 'System Setup' 'Regression Tests' )
[ $isLiveStack ] &&  opt=() ||  opt=('Toggle Stack Simulator \(currently: $stackSimON\)')
functions=('(doEditFile)' '(doViewLogs)' '(mc)' '(doManageTomcat)' '(doSystemSetup)' '(doRegressionTests)' )
[ $isLiveStack ] && opt2=() || opt2=('enableStackSim;curDwn=1')
genMenu "Main Menu ($scriptVersion)" "${menuItems[@]}" "${opt[@]}" "${functions[@]}" "${opt2[@]}"
echo $isLiveStack
}
#####################
# Launch
cd /home/powin
init
main

