#!/bin/bash
[ ! ${RUNREGRESSION_G} ] &&  RUNREGRESSION_G='RUNREGRESSION' ||  return 0
. $HOME/tools/snippets/bootstrap
#--------------------------------------------------------------------
# Make sure we have the Maven and Subversion are installed.
#--------------------------------------------------------------------
setupEnvironment () {
	# maven 
	if ! command -v mvn &> /dev/null; then
	  echo powin | sudo -S yum install maven -y
	fi
	# svn
	if ! command -v svn &> /dev/null; then
	  echo powin | sudo -S yum install svn -y
	fi

	if [ ! -e $SOURCE_CODE_PATH ]; then
	  mkdir $SOURCE_CODE_PATH
	fi
}

#-----------------------------------------------------------------------------------------------
# Run PowerCommandAppTest
#-----------------------------------------------------------------------------------------------
doPowerCommandAppTest () {
 local mytext='This function will run the regression test for the Power Command App'
 if  showYesNoDialog "$mytext" "Power Command App"
 then
  runRegression PowerCommandAppIntegrationTest
 fi
}
#-----------------------------------------------------------------------------------------------
# Run SunspecPowerAppTest
#-----------------------------------------------------------------------------------------------
doSunspecPowerAppTest () {
 local mytext='This function will run the regression test for the sunspec Power App.'
 if  showYesNoDialog "$mytext" "Sunspec Power App"
 then
  runRegression SunspecPowerAppIntegrationTest
 fi
}
#-----------------------------------------------------------------------------------------------
# Run Modbus Endpoints
#-----------------------------------------------------------------------------------------------

doModBusEndPoints () {
  local mytext='This function will run the regression test for the modbus endpoints suite.'
  if showYesNoDialog "$mytext" "Modbus End Points"
  then
     runRegression ModBusEndpointsSuite
  fi
}

#-----------------------------------------------------------------------------------------------
# Checkout the source
#-----------------------------------------------------------------------------------------------
doCheckoutSource () {
setupEnvironment

if [ ! -e $SOURCE_CODE_PATH ]; then
  mkdir $SOURCE_CODE_PATH
fi
cd $SOURCE_CODE_PATH
if [ -e "trunk" ]; then
	rm -dr trunk
fi
checkSubversionCredentials
svn checkout https://wush.net/svn/powin/sunspectests/trunk --username $SVNUSER  --password $SVNPASS
}

#-----------------------------------------------------------------------------------------------
# Run the regression test
#-----------------------------------------------------------------------------------------------
runRegression () {
   clear
   cd ${SOURCE_CODE_PATH}/trunk
   mvn clean integration-test -Dtest="$1"	
}

#***********************************************************************************************
# Regression Tests
#***********************************************************************************************

#-----------------------------------------------------------------------------------------------
# Regression Test Menu
#-----------------------------------------------------------------------------------------------
function doRegressionTests {
local menuItems=('Checkout Source' 'ModBus Endpoint Test' 'Sunspec Power App Test' 'Power Command App Test')
local functions=('(doCheckoutSource)' '(doModBusEndPoints);curDwn=1' '(doSunspecPowerAppTest);curDwn=1'  '(doPowerCommandAppTest);curDwn=1')
genMenu "RegressionTests" "${menuItems[@]}" "${functions[@]}"
}
