#!/bin/bash
. $HOME/tools/smoketestData/bootstrap
#-----------------------------------------------------------------------------------------------
# This script will read the latest versions of the apps given the major and minor versions.
# Pass the string "latests" to get the tip revisions.
#
#  Example Usage:    ./smoketestVersions 2 27
#                    ./smoketestVersions latest
#-----------------------------------------------------------------------------------------------



#-----------------------------------------------------------------------------------------------
# Start of script
#-----------------------------------------------------------------------------------------------
checkForNewVersion () {
 updateAppVersions
 readAppVersionsFromArchiva $1 $2
 checkNewVersion $1 $2

# Use this flag to detect that a new version has been built
if $NEW_VERSION_DETECTED;
then
  echo New version detected
else
  echo no changes
fi

}

#####################
# Launch


checkForNewVersion $1 $2

