#!/bin/bash
        #
	modZeroConfig() {
          if [ "$1" == true ] || [ "$1" == false ] ; then
	    echo powin | sudo -S  sed -i 's/\"simplifiedSafetyConfig\".*,/\"simplifiedSafetyConfig\" : '$1',/g' /etc/powin/configuration.json
          else echo invalid value [$1] passed to modZeroConfig, must be either 'true' or 'false' ; exit 1
          fi
	}

	restartTomcat() {
	   echo restarting Tomcat
	   echo powin | sudo -S  service tomcat restart 
	   echo powin | sudo -S truncate -s 0 $(locate catalina.out) 
	   echo powin | sudo -S tail -f $(locate catalina.out) | grep 'Server startup in'	
        }

	grep simplifiedSafetyConfig /etc/powin/configuration.json 

	if [ ! -z $1 ]; then
		echo
		read -rsn1 -p "Hit enter to turn simplifiedSaftetyConfig $1. Any other key to exit" EXECUTE
		echo
		if [[ $EXECUTE = "" ]] ; then
			
                        newVal=$1
			if [ "$1" == "on" ] ; then
                          echo enabling
                          newVal=true
			else if [ "$1" == "off" ] ; then
                             echo disabling
			     newVal=false
                          fi
			fi
                        modZeroConfig $newVal			

			echo powin | sudo -S grep simplifiedSafetyConfig /etc/powin/configuration.json

			restartTomcat
		fi

        fi
