package com.powin.modbusfiles.awe;

public class CellTemperatureLimits {
	public 	int CELL_HIGH_TEMPERATURE_ALARM_SET=0;
	public  int CELL_HIGH_TEMPERATURE_ALARM_CLEAR=0;
	public  int CELL_HIGH_TEMPERATURE_WARNING_SET=0;
	public  int CELL_HIGH_TEMPERATURE_WARNING_CLEAR=0;
	public  int CELL_HIGH_TEMPERATURE_WARRANTY_ALARM_SET=0;
	public  int CELL_HIGH_TEMPERATURE_WARRANTY_ALARM_CLEAR=0;
	public  int CELL_HIGH_TEMPERATURE_WARRANTY_WARNING_SET=0;
	public  int CELL_HIGH_TEMPERATURE_WARRANTY_WARNING_CLEAR=0;
	public  int CELL_LOW_TEMPERATURE_ALARM_SET=0;
	public  int CELL_LOW_TEMPERATURE_ALARM_CLEAR=0;
	public  int CELL_LOW_TEMPERATURE_WARNING_SET=0;
	public  int CELL_LOW_TEMPERATURE_WARNING_CLEAR=0;
	public  int CELL_LOW_TEMPERATURE_WARRANTY_ALARM_SET=0;
	public  int CELL_LOW_TEMPERATURE_WARRANTY_ALARM_CLEAR=0;
	public  int CELL_LOW_TEMPERATURE_WARRANTY_WARNING_SET=0;
	public  int CELL_LOW_TEMPERATURE_WARRANTY_WARNING_CLEAR=0;
	public  int CELL_HIGH_TEMPERATURE_DELTA_ALARM_SET=0;
	public  int CELL_HIGH_TEMPERATURE_DELTA_ALARM_CLEAR=0;
	public  int CELL_HIGH_TEMPERATURE_DELTA_WARNING_SET=0;
	public  int CELL_HIGH_TEMPERATURE_DELTA_WARNING_CLEAR=0;
	
	
	
	public CellTemperatureLimits get140() {
		this.CELL_HIGH_TEMPERATURE_ALARM_SET= 47;
		this.CELL_HIGH_TEMPERATURE_ALARM_CLEAR= 42;
		this.CELL_HIGH_TEMPERATURE_WARNING_SET=42;
		this.CELL_HIGH_TEMPERATURE_WARNING_CLEAR=37;
		this.CELL_HIGH_TEMPERATURE_WARRANTY_ALARM_SET=38;
		this.CELL_HIGH_TEMPERATURE_WARRANTY_ALARM_CLEAR=33;
		this.CELL_HIGH_TEMPERATURE_WARRANTY_WARNING_SET=33;
		this.CELL_HIGH_TEMPERATURE_WARRANTY_WARNING_CLEAR=28;
		this.CELL_LOW_TEMPERATURE_ALARM_SET=4;
		this.CELL_LOW_TEMPERATURE_ALARM_CLEAR=9;
		this.CELL_LOW_TEMPERATURE_WARNING_SET=9;
		this.CELL_LOW_TEMPERATURE_WARNING_CLEAR=14;
		this.CELL_LOW_TEMPERATURE_WARRANTY_ALARM_SET=4;
		this.CELL_LOW_TEMPERATURE_WARRANTY_ALARM_CLEAR=9;
		this.CELL_LOW_TEMPERATURE_WARRANTY_WARNING_SET=9;
		this.CELL_LOW_TEMPERATURE_WARRANTY_WARNING_CLEAR=14;
		this.CELL_HIGH_TEMPERATURE_DELTA_ALARM_SET=43;
		this.CELL_HIGH_TEMPERATURE_DELTA_ALARM_CLEAR=33;
		this.CELL_HIGH_TEMPERATURE_DELTA_WARNING_SET=33;
		this.CELL_HIGH_TEMPERATURE_DELTA_WARNING_CLEAR=23;	
		return this;	
	}
	
	public CellTemperatureLimits get225() {
		this.CELL_HIGH_TEMPERATURE_ALARM_SET= 47;
		this.CELL_HIGH_TEMPERATURE_ALARM_CLEAR= 42;
		this.CELL_HIGH_TEMPERATURE_WARNING_SET=42;
		this.CELL_HIGH_TEMPERATURE_WARNING_CLEAR=37;
		this.CELL_HIGH_TEMPERATURE_WARRANTY_ALARM_SET=38;
		this.CELL_HIGH_TEMPERATURE_WARRANTY_ALARM_CLEAR=33;
		this.CELL_HIGH_TEMPERATURE_WARRANTY_WARNING_SET=33;
		this.CELL_HIGH_TEMPERATURE_WARRANTY_WARNING_CLEAR=28;
		this.CELL_LOW_TEMPERATURE_ALARM_SET=4;
		this.CELL_LOW_TEMPERATURE_ALARM_CLEAR=9;
		this.CELL_LOW_TEMPERATURE_WARNING_SET=9;
		this.CELL_LOW_TEMPERATURE_WARNING_CLEAR=14;
		this.CELL_LOW_TEMPERATURE_WARRANTY_ALARM_SET=4;
		this.CELL_LOW_TEMPERATURE_WARRANTY_ALARM_CLEAR=9;
		this.CELL_LOW_TEMPERATURE_WARRANTY_WARNING_SET=9;
		this.CELL_LOW_TEMPERATURE_WARRANTY_WARNING_CLEAR=14;
		this.CELL_HIGH_TEMPERATURE_DELTA_ALARM_SET=43;
		this.CELL_HIGH_TEMPERATURE_DELTA_ALARM_CLEAR=33;
		this.CELL_HIGH_TEMPERATURE_DELTA_WARNING_SET=33;
		this.CELL_HIGH_TEMPERATURE_DELTA_WARNING_CLEAR=23;	
		return this;	
	}
	
	public CellTemperatureLimits get230() {
		this.CELL_HIGH_TEMPERATURE_ALARM_SET= 47;
		this.CELL_HIGH_TEMPERATURE_ALARM_CLEAR= 42;
		this.CELL_HIGH_TEMPERATURE_WARNING_SET=42;
		this.CELL_HIGH_TEMPERATURE_WARNING_CLEAR=37;
		this.CELL_HIGH_TEMPERATURE_WARRANTY_ALARM_SET=38;
		this.CELL_HIGH_TEMPERATURE_WARRANTY_ALARM_CLEAR=33;
		this.CELL_HIGH_TEMPERATURE_WARRANTY_WARNING_SET=33;
		this.CELL_HIGH_TEMPERATURE_WARRANTY_WARNING_CLEAR=28;
		this.CELL_LOW_TEMPERATURE_ALARM_SET=4;
		this.CELL_LOW_TEMPERATURE_ALARM_CLEAR=9;
		this.CELL_LOW_TEMPERATURE_WARNING_SET=9;
		this.CELL_LOW_TEMPERATURE_WARNING_CLEAR=14;
		this.CELL_LOW_TEMPERATURE_WARRANTY_ALARM_SET=4;
		this.CELL_LOW_TEMPERATURE_WARRANTY_ALARM_CLEAR=9;
		this.CELL_LOW_TEMPERATURE_WARRANTY_WARNING_SET=9;
		this.CELL_LOW_TEMPERATURE_WARRANTY_WARNING_CLEAR=14;
		this.CELL_HIGH_TEMPERATURE_DELTA_ALARM_SET=43;
		this.CELL_HIGH_TEMPERATURE_DELTA_ALARM_CLEAR=33;
		this.CELL_HIGH_TEMPERATURE_DELTA_WARNING_SET=33;
		this.CELL_HIGH_TEMPERATURE_DELTA_WARNING_CLEAR=23;	
		return this;	
	}
	
	public CellTemperatureLimits() {
		// TODO Auto-generated constructor stub
	}
}
