package com.powin.modbusfiles.future;

import com.powin.modbusfiles.awe.CellVoltageLimits;

public class CellVoltageLimits141 {
	
	public static int CELL_HIGH_VOLTAGE_ALARM_SET=3650;
	public static int CELL_HIGH_VOLTAGE_ALARM_CLEAR=3600;
	public static int CELL_HIGH_VOLTAGE_WARNING_SET=3600;
	public static int CELL_HIGH_VOLTAGE_WARNING_CLEAR=3520;
	public static int CELL_HIGH_VOLTAGE_WARRANTY_ALARM_SET=3650;
	public static int CELL_HIGH_VOLTAGE_WARRANTY_ALARM_CLEAR=3600;
	public static int CELL_HIGH_VOLTAGE_WARRANTY_WARNING_SET=3600;
	public static int CELL_HIGH_VOLTAGE_WARRANTY_WARNING_CLEAR=3500;
	public static int CELL_LOW_VOLTAGE_ALARM_SET=2500;
	public static int CELL_LOW_VOLTAGE_ALARM_CLEAR=2550;
	public static int CELL_LOW_VOLTAGE_WARNING_SET=2800;
	public static int CELL_LOW_VOLTAGE_WARNING_CLEAR=2900;
	public static int CELL_LOW_VOLTAGE_WARRANTY_ALARM_SET=2500;
	public static int CELL_LOW_VOLTAGE_WARRANTY_ALARM_CLEAR=2700;
	public static int CELL_LOW_VOLTAGE_WARRANTY_WARNING_SET=2700;
	public static int CELL_LOW_VOLTAGE_WARRANTY_WARNING_CLEAR=2800;
	public static int CELL_HIGH_VOLTAGE_DELTA_ALARM_SET=1000;
	public static int CELL_HIGH_VOLTAGE_DELTA_ALARM_CLEAR=800;
	public static int CELL_HIGH_VOLTAGE_DELTA_WARNING_SET=800;
	public static int CELL_HIGH_VOLTAGE_DELTA_WARNING_CLEAR=600;	
	
	public CellVoltageLimits populate(){
		CellVoltageLimits cvl = new CellVoltageLimits();
		
		cvl.CELL_HIGH_VOLTAGE_ALARM_CLEAR= CELL_HIGH_VOLTAGE_ALARM_CLEAR;
		cvl.CELL_HIGH_VOLTAGE_WARNING_SET=CELL_HIGH_VOLTAGE_WARNING_SET;
		cvl.CELL_HIGH_VOLTAGE_WARNING_CLEAR=CELL_HIGH_VOLTAGE_WARNING_CLEAR;
		cvl.CELL_HIGH_VOLTAGE_WARRANTY_ALARM_SET=CELL_HIGH_VOLTAGE_WARRANTY_ALARM_SET;
		cvl.CELL_HIGH_VOLTAGE_WARRANTY_ALARM_CLEAR=CELL_HIGH_VOLTAGE_WARRANTY_ALARM_CLEAR;
		cvl.CELL_HIGH_VOLTAGE_WARRANTY_WARNING_SET=CELL_HIGH_VOLTAGE_WARRANTY_WARNING_SET;
		cvl.CELL_HIGH_VOLTAGE_WARRANTY_WARNING_CLEAR=CELL_HIGH_VOLTAGE_WARRANTY_WARNING_CLEAR;
		cvl.CELL_LOW_VOLTAGE_ALARM_SET=CELL_LOW_VOLTAGE_ALARM_SET;
		cvl.CELL_LOW_VOLTAGE_ALARM_CLEAR=CELL_LOW_VOLTAGE_ALARM_CLEAR;
		cvl.CELL_LOW_VOLTAGE_WARNING_SET=CELL_LOW_VOLTAGE_WARNING_SET;
		cvl.CELL_LOW_VOLTAGE_WARNING_CLEAR=CELL_LOW_VOLTAGE_WARNING_CLEAR;
		cvl.CELL_LOW_VOLTAGE_WARRANTY_ALARM_SET=CELL_LOW_VOLTAGE_WARRANTY_ALARM_SET;
		cvl.CELL_LOW_VOLTAGE_WARRANTY_ALARM_CLEAR=CELL_LOW_VOLTAGE_WARRANTY_ALARM_CLEAR;
		cvl.CELL_LOW_VOLTAGE_WARRANTY_WARNING_SET=CELL_LOW_VOLTAGE_WARRANTY_WARNING_SET;
		cvl.CELL_LOW_VOLTAGE_WARRANTY_WARNING_CLEAR=CELL_LOW_VOLTAGE_WARRANTY_WARNING_CLEAR;
		cvl.CELL_HIGH_VOLTAGE_DELTA_ALARM_SET=CELL_HIGH_VOLTAGE_DELTA_ALARM_SET;
		cvl.CELL_HIGH_VOLTAGE_DELTA_ALARM_CLEAR=CELL_HIGH_VOLTAGE_DELTA_ALARM_CLEAR;
		cvl.CELL_HIGH_VOLTAGE_DELTA_WARNING_SET=CELL_HIGH_VOLTAGE_DELTA_WARNING_SET;
		cvl.CELL_HIGH_VOLTAGE_DELTA_WARNING_CLEAR=CELL_HIGH_VOLTAGE_DELTA_WARNING_CLEAR;
		return 	cvl;
	}
		
	
}