package com.powin.modbusfiles.future;

import com.powin.modbusfiles.awe.CellVoltageLimits;

public class CellVoltageLimits140 {
		public  int CELL_HIGH_VOLTAGE_ALARM_SET=3650;
		public  int CELL_HIGH_VOLTAGE_ALARM_CLEAR=3600;
		public  int CELL_HIGH_VOLTAGE_WARNING_SET=3600;
		public  int CELL_HIGH_VOLTAGE_WARNING_CLEAR=3520;
		public  int CELL_HIGH_VOLTAGE_WARRANTY_ALARM_SET=3650;
		public  int CELL_HIGH_VOLTAGE_WARRANTY_ALARM_CLEAR=3600;
		public  int CELL_HIGH_VOLTAGE_WARRANTY_WARNING_SET=3600;
		public  int CELL_HIGH_VOLTAGE_WARRANTY_WARNING_CLEAR=3500;
		public  int CELL_LOW_VOLTAGE_ALARM_SET=2500;
		public  int CELL_LOW_VOLTAGE_ALARM_CLEAR=2550;
		public  int CELL_LOW_VOLTAGE_WARNING_SET=2800;
		public  int CELL_LOW_VOLTAGE_WARNING_CLEAR=2900;
		public  int CELL_LOW_VOLTAGE_WARRANTY_ALARM_SET=2500;
		public  int CELL_LOW_VOLTAGE_WARRANTY_ALARM_CLEAR=2700;
		public  int CELL_LOW_VOLTAGE_WARRANTY_WARNING_SET=2700;
		public  int CELL_LOW_VOLTAGE_WARRANTY_WARNING_CLEAR=2800;
		public  int CELL_HIGH_VOLTAGE_DELTA_ALARM_SET=1000;
		public  int CELL_HIGH_VOLTAGE_DELTA_ALARM_CLEAR=800;
		public  int CELL_HIGH_VOLTAGE_DELTA_WARNING_SET=800;
		public  int CELL_HIGH_VOLTAGE_DELTA_WARNING_CLEAR=600;	
		
		public CellVoltageLimits get140() {
			return null;
		}
	}