package com.powin.modbusfiles.awe;

public class CellVoltageLimits {
	public 	int CELL_HIGH_VOLTAGE_ALARM_SET=0;
	public  int CELL_HIGH_VOLTAGE_ALARM_CLEAR=0;
	public  int CELL_HIGH_VOLTAGE_WARNING_SET=0;
	public  int CELL_HIGH_VOLTAGE_WARNING_CLEAR=0;
	public  int CELL_HIGH_VOLTAGE_WARRANTY_ALARM_SET=0;
	public  int CELL_HIGH_VOLTAGE_WARRANTY_ALARM_CLEAR=0;
	public  int CELL_HIGH_VOLTAGE_WARRANTY_WARNING_SET=0;
	public  int CELL_HIGH_VOLTAGE_WARRANTY_WARNING_CLEAR=0;
	public  int CELL_LOW_VOLTAGE_ALARM_SET=0;
	public  int CELL_LOW_VOLTAGE_ALARM_CLEAR=0;
	public  int CELL_LOW_VOLTAGE_WARNING_SET=0;
	public  int CELL_LOW_VOLTAGE_WARNING_CLEAR=0;
	public  int CELL_LOW_VOLTAGE_WARRANTY_ALARM_SET=0;
	public  int CELL_LOW_VOLTAGE_WARRANTY_ALARM_CLEAR=0;
	public  int CELL_LOW_VOLTAGE_WARRANTY_WARNING_SET=0;
	public  int CELL_LOW_VOLTAGE_WARRANTY_WARNING_CLEAR=0;
	public  int CELL_HIGH_VOLTAGE_DELTA_ALARM_SET=0;
	public  int CELL_HIGH_VOLTAGE_DELTA_ALARM_CLEAR=0;
	public  int CELL_HIGH_VOLTAGE_DELTA_WARNING_SET=0;
	public  int CELL_HIGH_VOLTAGE_DELTA_WARNING_CLEAR=0;
	
	
	
	public CellVoltageLimits get140() {
		this.CELL_HIGH_VOLTAGE_ALARM_SET= 3650;
		this.CELL_HIGH_VOLTAGE_ALARM_CLEAR= 3600;
		this.CELL_HIGH_VOLTAGE_WARNING_SET=3600;
		this.CELL_HIGH_VOLTAGE_WARNING_CLEAR=3520;
		this.CELL_HIGH_VOLTAGE_WARRANTY_ALARM_SET=3650;
		this.CELL_HIGH_VOLTAGE_WARRANTY_ALARM_CLEAR=3600;
		this.CELL_HIGH_VOLTAGE_WARRANTY_WARNING_SET=3600;
		this.CELL_HIGH_VOLTAGE_WARRANTY_WARNING_CLEAR=3500;
		this.CELL_LOW_VOLTAGE_ALARM_SET=2500;
		this.CELL_LOW_VOLTAGE_ALARM_CLEAR=2550;
		this.CELL_LOW_VOLTAGE_WARNING_SET=2800;
		this.CELL_LOW_VOLTAGE_WARNING_CLEAR=2900;
		this.CELL_LOW_VOLTAGE_WARRANTY_ALARM_SET=2500;
		this.CELL_LOW_VOLTAGE_WARRANTY_ALARM_CLEAR=2700;
		this.CELL_LOW_VOLTAGE_WARRANTY_WARNING_SET=2700;
		this.CELL_LOW_VOLTAGE_WARRANTY_WARNING_CLEAR=2800;
		this.CELL_HIGH_VOLTAGE_DELTA_ALARM_SET=1000;
		this.CELL_HIGH_VOLTAGE_DELTA_ALARM_CLEAR=800;
		this.CELL_HIGH_VOLTAGE_DELTA_WARNING_SET=800;
		this.CELL_HIGH_VOLTAGE_DELTA_WARNING_CLEAR=600;	
		return this;	
	}
	
	public CellVoltageLimits get225() {
		this.CELL_HIGH_VOLTAGE_ALARM_SET=3651;
		this.CELL_HIGH_VOLTAGE_ALARM_CLEAR=3601;
		this.CELL_HIGH_VOLTAGE_WARNING_SET=3601;
		this.CELL_HIGH_VOLTAGE_WARNING_CLEAR=3521;
		this.CELL_HIGH_VOLTAGE_WARRANTY_ALARM_SET=3651;
		this.CELL_HIGH_VOLTAGE_WARRANTY_ALARM_CLEAR=3601;
		this.CELL_HIGH_VOLTAGE_WARRANTY_WARNING_SET=3601;
		this.CELL_HIGH_VOLTAGE_WARRANTY_WARNING_CLEAR=3501;
		this.CELL_LOW_VOLTAGE_ALARM_SET=2501;
		this.CELL_LOW_VOLTAGE_ALARM_CLEAR=2551;
		this.CELL_LOW_VOLTAGE_WARNING_SET=2801;
		this.CELL_LOW_VOLTAGE_WARNING_CLEAR=2901;
		this.CELL_LOW_VOLTAGE_WARRANTY_ALARM_SET=2501;
		this.CELL_LOW_VOLTAGE_WARRANTY_ALARM_CLEAR=2701;
		this.CELL_LOW_VOLTAGE_WARRANTY_WARNING_SET=2701;
		this.CELL_LOW_VOLTAGE_WARRANTY_WARNING_CLEAR=2801;
		this.CELL_HIGH_VOLTAGE_DELTA_ALARM_SET=1001;
		this.CELL_HIGH_VOLTAGE_DELTA_ALARM_CLEAR=801;
		this.CELL_HIGH_VOLTAGE_DELTA_WARNING_SET=801;
		this.CELL_HIGH_VOLTAGE_DELTA_WARNING_CLEAR=601;	
		return this;	
	}
	
//Trial code to see if we can get 140 and 225 data more elegantly
	
	public static CellVoltageLimits populate(){
		CellVoltageLimits cvl = new CellVoltageLimits();
		cvl.CELL_HIGH_VOLTAGE_ALARM_CLEAR= cvl.CELL_HIGH_VOLTAGE_ALARM_CLEAR;
		cvl.CELL_HIGH_VOLTAGE_WARNING_SET=cvl.CELL_HIGH_VOLTAGE_WARNING_SET;
		cvl.CELL_HIGH_VOLTAGE_WARNING_CLEAR=cvl.CELL_HIGH_VOLTAGE_WARNING_CLEAR;
		cvl.CELL_HIGH_VOLTAGE_WARRANTY_ALARM_SET=cvl.CELL_HIGH_VOLTAGE_WARRANTY_ALARM_SET;
		cvl.CELL_HIGH_VOLTAGE_WARRANTY_ALARM_CLEAR=cvl.CELL_HIGH_VOLTAGE_WARRANTY_ALARM_CLEAR;
		cvl.CELL_HIGH_VOLTAGE_WARRANTY_WARNING_SET=cvl.CELL_HIGH_VOLTAGE_WARRANTY_WARNING_SET;
		cvl.CELL_HIGH_VOLTAGE_WARRANTY_WARNING_CLEAR=cvl.CELL_HIGH_VOLTAGE_WARRANTY_WARNING_CLEAR;
		cvl.CELL_LOW_VOLTAGE_ALARM_SET=cvl.CELL_LOW_VOLTAGE_ALARM_SET;
		cvl.CELL_LOW_VOLTAGE_ALARM_CLEAR=cvl.CELL_LOW_VOLTAGE_ALARM_CLEAR;
		cvl.CELL_LOW_VOLTAGE_WARNING_SET=cvl.CELL_LOW_VOLTAGE_WARNING_SET;
		cvl.CELL_LOW_VOLTAGE_WARNING_CLEAR=cvl.CELL_LOW_VOLTAGE_WARNING_CLEAR;
		cvl.CELL_LOW_VOLTAGE_WARRANTY_ALARM_SET=cvl.CELL_LOW_VOLTAGE_WARRANTY_ALARM_SET;
		cvl.CELL_LOW_VOLTAGE_WARRANTY_ALARM_CLEAR=cvl.CELL_LOW_VOLTAGE_WARRANTY_ALARM_CLEAR;
		cvl.CELL_LOW_VOLTAGE_WARRANTY_WARNING_SET=cvl.CELL_LOW_VOLTAGE_WARRANTY_WARNING_SET;
		cvl.CELL_LOW_VOLTAGE_WARRANTY_WARNING_CLEAR=cvl.CELL_LOW_VOLTAGE_WARRANTY_WARNING_CLEAR;
		cvl.CELL_HIGH_VOLTAGE_DELTA_ALARM_SET=cvl.CELL_HIGH_VOLTAGE_DELTA_ALARM_SET;
		cvl.CELL_HIGH_VOLTAGE_DELTA_ALARM_CLEAR=cvl.CELL_HIGH_VOLTAGE_DELTA_ALARM_CLEAR;
		cvl.CELL_HIGH_VOLTAGE_DELTA_WARNING_SET=cvl.CELL_HIGH_VOLTAGE_DELTA_WARNING_SET;
		cvl.CELL_HIGH_VOLTAGE_DELTA_WARNING_CLEAR=cvl.CELL_HIGH_VOLTAGE_DELTA_WARNING_CLEAR;
		return 	cvl;
	}	
	public  CellVoltageLimits(CellVoltageLimits toCopy) {
		this.CELL_HIGH_VOLTAGE_ALARM_CLEAR=toCopy.CELL_HIGH_VOLTAGE_ALARM_CLEAR;
		this.CELL_HIGH_VOLTAGE_WARNING_SET=toCopy.CELL_HIGH_VOLTAGE_WARNING_SET;
		this.CELL_HIGH_VOLTAGE_WARNING_CLEAR=toCopy.CELL_HIGH_VOLTAGE_WARNING_CLEAR;
		this.CELL_HIGH_VOLTAGE_WARRANTY_ALARM_SET=toCopy.CELL_HIGH_VOLTAGE_WARRANTY_ALARM_SET;
		this.CELL_HIGH_VOLTAGE_WARRANTY_ALARM_CLEAR=toCopy.CELL_HIGH_VOLTAGE_WARRANTY_ALARM_CLEAR;
		this.CELL_HIGH_VOLTAGE_WARRANTY_WARNING_SET=toCopy.CELL_HIGH_VOLTAGE_WARRANTY_WARNING_SET;
		this.CELL_HIGH_VOLTAGE_WARRANTY_WARNING_CLEAR=toCopy.CELL_HIGH_VOLTAGE_WARRANTY_WARNING_CLEAR;
		this.CELL_LOW_VOLTAGE_ALARM_SET=toCopy.CELL_LOW_VOLTAGE_ALARM_SET;
		this.CELL_LOW_VOLTAGE_ALARM_CLEAR=toCopy.CELL_LOW_VOLTAGE_ALARM_CLEAR;
		this.CELL_LOW_VOLTAGE_WARNING_SET=toCopy.CELL_LOW_VOLTAGE_WARNING_SET;
		this.CELL_LOW_VOLTAGE_WARNING_CLEAR=toCopy.CELL_LOW_VOLTAGE_WARNING_CLEAR;
		this.CELL_LOW_VOLTAGE_WARRANTY_ALARM_SET=toCopy.CELL_LOW_VOLTAGE_WARRANTY_ALARM_SET;
		this.CELL_LOW_VOLTAGE_WARRANTY_ALARM_CLEAR=toCopy.CELL_LOW_VOLTAGE_WARRANTY_ALARM_CLEAR;
		this.CELL_LOW_VOLTAGE_WARRANTY_WARNING_SET=toCopy.CELL_LOW_VOLTAGE_WARRANTY_WARNING_SET;
		this.CELL_LOW_VOLTAGE_WARRANTY_WARNING_CLEAR=toCopy.CELL_LOW_VOLTAGE_WARRANTY_WARNING_CLEAR;
		this.CELL_HIGH_VOLTAGE_DELTA_ALARM_SET=toCopy.CELL_HIGH_VOLTAGE_DELTA_ALARM_SET;
		this.CELL_HIGH_VOLTAGE_DELTA_ALARM_CLEAR=toCopy.CELL_HIGH_VOLTAGE_DELTA_ALARM_CLEAR;
		this.CELL_HIGH_VOLTAGE_DELTA_WARNING_SET=toCopy.CELL_HIGH_VOLTAGE_DELTA_WARNING_SET;
		this.CELL_HIGH_VOLTAGE_DELTA_WARNING_CLEAR=toCopy.CELL_HIGH_VOLTAGE_DELTA_WARNING_CLEAR;
	}

	public CellVoltageLimits() {
		// TODO Auto-generated constructor stub
	}
}
